## 단층 퍼셉트론

In [1]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x1 = df.iloc[:, 0].values
        self.x2 = df.iloc[:, 1].values
        self.y = df.iloc[:, 2].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x1[index], self.x2[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y

    def __len__(self):
        return self.length

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.layer(x)
        return x

In [2]:
train_dataset = CustomDataset("../datasets/perceptron.csv")
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [ ]:
for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")

/var/folders/8l/dq9nhgmx5gj01xrwhwzb41s40000gn/T/ipykernel_1261/3067956643.py:17: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
/var/folders/8l/dq9nhgmx5gj01xrwhwzb41s40000gn/T/ipykernel_1261/3067956643.py:18: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


Epoch : 1000, Cost : 0.692
Epoch : 2000, Cost : 0.692
Epoch : 3000, Cost : 0.692
Epoch : 4000, Cost : 0.692
Epoch : 5000, Cost : 0.692
Epoch : 6000, Cost : 0.691
Epoch : 7000, Cost : 0.692
Epoch : 8000, Cost : 0.692
Epoch : 9000, Cost : 0.692


In [6]:
with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)

    print("---------")
    print(outputs)
    print(outputs <= 0.5)

---------
tensor([[0.4675],
        [0.5003],
        [0.5033],
        [0.5361]])
tensor([[ True],
        [False],
        [False],
        [False]])


## 다중 퍼셉트론

In [14]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Sequential(
            nn.Linear(2, 2),
            nn.Sigmoid()
        )

        self.layer2 = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )


    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

In [15]:
train_dataset = CustomDataset("../datasets/perceptron.csv")
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

In [16]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [17]:
for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")

/var/folders/8l/dq9nhgmx5gj01xrwhwzb41s40000gn/T/ipykernel_492/3067956643.py:17: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
/var/folders/8l/dq9nhgmx5gj01xrwhwzb41s40000gn/T/ipykernel_492/3067956643.py:18: DeprecationWarning: In future, it will be an error for 'np.bool' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


Epoch : 1000, Cost : 0.690
Epoch : 2000, Cost : 0.605
Epoch : 3000, Cost : 0.424
Epoch : 4000, Cost : 0.370
Epoch : 5000, Cost : 0.356
Epoch : 6000, Cost : 0.350
Epoch : 7000, Cost : 0.344
Epoch : 8000, Cost : 0.345
Epoch : 9000, Cost : 0.339
Epoch : 10000, Cost : 0.341


In [18]:
with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)

    print("---------")
    print(outputs)
    print(outputs <= 0.5)

---------
tensor([[0.0049],
        [0.9921],
        [0.5178],
        [0.5231]])
tensor([[ True],
        [False],
        [False],
        [False]])
