## Lecture 3 - Python for Data Analytics (Numpy)

### numpy 라이브러리 버전을 확인

In [2]:
import numpy as np

print(np.__version__)

1.26.4


### Creating a basic array

In [3]:
a = np.array([1,2,3])

print(a)

[1 2 3]


### Array types

In [4]:
arr = np.array(42)
print(arr)

42


In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Initial Placeholders

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(3)

array([3., 2., 1.])

In [12]:
np.full(3, 7)

array([7, 7, 7])

In [13]:
np.full(shape = 3, fill_value = 7)

array([7, 7, 7])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.random((2,2))

array([[0.69112705, 0.69647815],
       [0.80027557, 0.94258722]])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [19]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Data types in numpy

In [20]:
arr = np.array([0, 1, 2, 3])
print(arr.dtype)

int64


In [21]:
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [22]:
arr = np.array(['a', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [23]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


### Find number of dimensions of the array

In [26]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])
print(array_example.ndim)

3


### Find the total number of elements in the array

In [27]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])
print(array_example.size)

24


### Find the length or the number of elements in the array

In [28]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])
print(len(array_example))

3


### Find the shape of your array

In [30]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])
print(array_example.shape)

(3, 2, 4)


### Array indexing

In [32]:
arr = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr[0, 1, 2])

6


### Reshaping an array

In [33]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### Flattening the arrays

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### Slicing

In [35]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [37]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [39]:
arr = np.array([[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


### Joining arrays

In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


### Joining arrays using stack() function

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Split numpy arrays

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Copy numpy array

In [43]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### Search in numpy array

In [45]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


### Search in numpy array

In [46]:
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 5  6  7  8  9 10]


### Intersection of two numpy arrays

In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### Difference between two numpy arrays

In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Sorting numpy array

In [49]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


### Getting unique numbers from numpy array

In [50]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


### Basic arithmetic operations

In [51]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)

[2 3]


### Basic arithmetic operations

In [53]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


### Broadcasting

In [54]:
data = np.array([1.0, 2.0])
print(data * 1.6)

[1.6 3.2]


### Other useful operations

In [55]:
print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0
